---
- name: create a new  tomcat group
  group:
    name: tomcat
    state: present


- name: create a new  tomcat user
  user:
    name: tomcat
    state: present
    shell: /bin/false
    group: tomcat
    home: /opt/tomcat